<script lang="ts">
	import { enhance } from '$app/forms';
	import { env } from '$env/dynamic/public';
	import type { ActionData, PageData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();

	let creating = $state(false);

	type RevealedSecret = {
		label: string;
		keyId: string;
		secret: string;
		mode: 'created' | 'rotated';
	};
	let revealedSecret = $state<RevealedSecret | null>(null);
	let copyFeedback = $state(false);

	// A local, live-updatable copy of the user list: form actions (create/
	// toggle/rotate/delete) refresh `data.users` via SvelteKit's own reload,
	// which this re-syncs from; the 5s poll below only patches `online`/
	// `lastSeenAt` in place on top of that, since those are the only fields
	// that change on their own between actions.
	let users = $state(data.users.map((u) => ({ ...u })));
	$effect(() => {
		users = data.users.map((u) => ({ ...u }));
	});

	$effect(() => {
		const interval = setInterval(async () => {
			let statuses: { id: string; online: boolean; lastSeenAt: string | null }[];
			try {
				const res = await fetch('/status');
				if (!res.ok) return;
				statuses = await res.json();
			} catch {
				return; // transient network error; try again on the next tick
			}
			const byId = new Map(statuses.map((s) => [s.id, s]));
			users = users.map((u) => {
				const s = byId.get(u.id);
				return s ? { ...u, online: s.online, lastSeenAt: s.lastSeenAt } : u;
			});
		}, 5000);
		return () => clearInterval(interval);
	});

	let enabledCount = $derived(users.filter((u) => u.enabled).length);

	$effect(() => {
		if (form && 'created' in form && form.created) {
			revealedSecret = {
				label: form.created.label,
				keyId: form.created.keyId,
				secret: form.created.secret,
				mode: 'created'
			};
		} else if (form && 'rotated' in form && form.rotated) {
			revealedSecret = {
				label: form.rotated.label,
				keyId: form.rotated.keyId,
				secret: form.rotated.secret,
				mode: 'rotated'
			};
		}
	});

	function dismissSecret() {
		revealedSecret = null;
		copyFeedback = false;
	}

	async function copySecret() {
		if (!revealedSecret) return;
		try {
			await navigator.clipboard.writeText(revealedSecret.secret);
			copyFeedback = true;
			setTimeout(() => (copyFeedback = false), 1500);
		} catch {
			// clipboard API can be unavailable (insecure context, permissions) - not fatal,
			// the admin can still select-and-copy the text manually.
		}
	}

	/** Builds this user's client config.toml and triggers a browser download. Only
	 * possible right after create/rotate, since that's the only time the plaintext
	 * secret is ever available at all. */
	function downloadConfig() {
		if (!revealedSecret) return;
		const host = env.PUBLIC_MC_HOST || '127.0.0.1';
		const port = env.PUBLIC_MC_PORT || '25565';
		const toml = `# Generated by the mcvpn admin panel for "${revealedSecret.label}".
# Fill in / adjust proxy_listen below if this client shouldn't use the default.
server_host = "${host}"
server_port = ${port}
username_prefix = "mcvpn_"
proxy_listen = "127.0.0.1:8080"
key_id = "${revealedSecret.keyId}"
key_secret = "${revealedSecret.secret}"
`;
		const blob = new Blob([toml], { type: 'application/toml' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		const safeLabel = revealedSecret.label.replace(/[^a-z0-9_-]+/gi, '_');
		a.href = url;
		a.download = `mcvpn-${safeLabel}.toml`;
		a.click();
		URL.revokeObjectURL(url);
	}

	function truncateHex(value: string, head = 8, tail = 6) {
		if (value.length <= head + tail + 1) return value;
		return `${value.slice(0, head)}…${value.slice(-tail)}`;
	}

	function formatDate(value: string | null) {
		if (!value) return '—';
		const d = new Date(value);
		return Number.isNaN(d.getTime()) ? value : d.toLocaleString();
	}

	function confirmDelete(label: string) {
		return confirm(`Delete VPN user "${label}"? This cannot be undone.`);
	}

	function confirmRotate(label: string) {
		return confirm(
			`Rotate the secret for "${label}"? The current secret will stop working immediately.`
		);
	}
</script>

<svelte:head>
	<title>VPN users — mcvpn admin</title>
</svelte:head>

<div class="page-head">
	<h1>VPN users</h1>
	<p class="lede">Manage tunnel identities, rotate secrets, and control access.</p>
</div>

<div class="stat-strip">
	<div class="stat-card">
		<span class="stat-label">Total users</span>
		<span class="stat-value">{users.length}</span>
	</div>
	<div class="stat-card">
		<span class="stat-label">Enabled</span>
		<span class="stat-value stat-enabled">{enabledCount}</span>
	</div>
	<div class="stat-card">
		<span class="stat-label">Disabled</span>
		<span class="stat-value stat-disabled">{users.length - enabledCount}</span>
	</div>
</div>

{#if revealedSecret}
	<div class="callout warning secret-reveal">
		<div class="secret-header">
			<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
				<path
					d="M8 1.5 14.5 5v6L8 14.5 1.5 11V5L8 1.5Z"
					stroke="currentColor"
					stroke-width="1.3"
					stroke-linejoin="round"
				/>
				<path d="M8 7.2v2.6M8 11.6h.007" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" />
			</svg>
			<p class="secret-title">
				{revealedSecret.mode === 'created' ? 'New user created' : 'Secret rotated'}: <strong
					>{revealedSecret.label}</strong
				>
			</p>
		</div>
		<p class="secret-copy">
			This secret is shown <strong>once</strong> and cannot be retrieved again. Copy it now and store
			it securely.
		</p>
		<div class="secret-row">
			<code class="mono secret-value">{revealedSecret.secret}</code>
			<button type="button" onclick={copySecret} class="copy-btn" class:copied={copyFeedback}>
				{#if copyFeedback}
					<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path
							d="M3.5 8.5 6.5 11.5 12.5 4.5"
							stroke="currentColor"
							stroke-width="1.6"
							stroke-linecap="round"
							stroke-linejoin="round"
						/>
					</svg>
					Copied
				{:else}
					<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
						<rect
							x="5.5"
							y="5.5"
							width="8"
							height="9"
							rx="1.5"
							stroke="currentColor"
							stroke-width="1.4"
						/>
						<path
							d="M2.75 10.5v-6a1.75 1.75 0 0 1 1.75-1.75h5"
							stroke="currentColor"
							stroke-width="1.4"
							stroke-linecap="round"
						/>
					</svg>
					Copy
				{/if}
			</button>
		</div>
		<div class="secret-actions">
			<button type="button" class="ghost download-btn" onclick={downloadConfig}>
				<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path
						d="M8 2.5v7.2M5 6.9 8 9.7l3-2.8M3.5 12.5h9"
						stroke="currentColor"
						stroke-width="1.4"
						stroke-linecap="round"
						stroke-linejoin="round"
					/>
				</svg>
				Download config.toml
			</button>
			<button type="button" class="ghost dismiss-btn" onclick={dismissSecret}>Dismiss</button>
		</div>
	</div>
{/if}

<section class="create-user card">
	<h2>Add user</h2>
	<form
		method="POST"
		action="?/create"
		use:enhance={() => {
			creating = true;
			return async ({ update }) => {
				await update();
				creating = false;
			};
		}}
	>
		<label>
			Label
			<input type="text" name="label" placeholder="e.g. alice's laptop" required />
		</label>
		<button type="submit" class="primary" disabled={creating}>
			{#if !creating}
				<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path
						d="M8 3.5v9M3.5 8h9"
						stroke="currentColor"
						stroke-width="1.6"
						stroke-linecap="round"
					/>
				</svg>
			{/if}
			{creating ? 'Creating…' : 'Create user'}
		</button>
	</form>
	{#if form && 'createError' in form && form.createError}
		<p class="error" role="alert">{form.createError}</p>
	{/if}
</section>

{#if form && 'actionError' in form && form.actionError}
	<p class="error" role="alert">{form.actionError}</p>
{/if}

<section class="users-table">
	{#if users.length === 0}
		<p class="empty">No VPN users yet.</p>
	{:else}
		<div class="table-scroll">
			<table>
				<thead>
					<tr>
						<th>Label</th>
						<th>Key ID</th>
						<th>Status</th>
						<th>Online</th>
						<th>Created</th>
						<th>Last seen</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{#each users as user (user.id)}
						<tr>
							<td>{user.label}</td>
							<td>
								<code class="mono" title={user.keyId}>{truncateHex(user.keyId)}</code>
							</td>
							<td>
								<span class="badge {user.enabled ? 'enabled' : 'disabled'}">
									{user.enabled ? 'Enabled' : 'Disabled'}
								</span>
							</td>
							<td>
								<span class="badge {user.online ? 'enabled' : 'disabled'}">
									{user.online ? 'Online' : 'Offline'}
								</span>
							</td>
							<td>{formatDate(user.createdAt)}</td>
							<td>{formatDate(user.lastSeenAt)}</td>
							<td class="row-actions">
								<form method="POST" action="?/toggle" use:enhance>
									<input type="hidden" name="id" value={user.id} />
									<input type="hidden" name="enabled" value={(!user.enabled).toString()} />
									<button type="submit" class="ghost" title={user.enabled ? 'Disable' : 'Enable'}>
										{#if user.enabled}
											<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
												<circle cx="8" cy="8" r="5.5" stroke="currentColor" stroke-width="1.4" />
												<path d="M5.8 5.8 10.2 10.2" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" />
											</svg>
										{:else}
											<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
												<circle cx="8" cy="8" r="5.5" stroke="currentColor" stroke-width="1.4" />
												<path d="M5.8 8.3 7.2 9.7 10.3 6.5" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" />
											</svg>
										{/if}
										{user.enabled ? 'Disable' : 'Enable'}
									</button>
								</form>
								<form
									method="POST"
									action="?/rotate"
									use:enhance
									onsubmit={(e) => {
										if (!confirmRotate(user.label)) e.preventDefault();
									}}
								>
									<input type="hidden" name="id" value={user.id} />
									<button type="submit" class="ghost" title="Rotate secret">
										<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												d="M13 8a5 5 0 1 1-1.6-3.67"
												stroke="currentColor"
												stroke-width="1.4"
												stroke-linecap="round"
											/>
											<path
												d="M13 3v3.2h-3.2"
												stroke="currentColor"
												stroke-width="1.4"
												stroke-linecap="round"
												stroke-linejoin="round"
											/>
										</svg>
										Rotate
									</button>
								</form>
								<form
									method="POST"
									action="?/delete"
									use:enhance
									onsubmit={(e) => {
										if (!confirmDelete(user.label)) e.preventDefault();
									}}
								>
									<input type="hidden" name="id" value={user.id} />
									<button type="submit" class="danger" title="Delete">
										<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path
												d="M3.5 5h9M6.5 5V3.6c0-.55.45-1 1-1h1c.55 0 1 .45 1 1V5m-5.5 0 .5 8.2c.03.44.4.8.85.8h4.3c.45 0 .82-.36.85-.8L12.5 5"
												stroke="currentColor"
												stroke-width="1.4"
												stroke-linecap="round"
												stroke-linejoin="round"
											/>
										</svg>
										Delete
									</button>
								</form>
							</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	{/if}
</section>

<style>
	.page-head {
		margin-bottom: 1.5rem;
	}

	h1 {
		margin: 0 0 0.3rem;
	}

	.lede {
		margin: 0;
		color: var(--text-muted);
		font-size: 0.9rem;
	}

	.stat-strip {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
		gap: 0.9rem;
		margin-bottom: 1.75rem;
		max-width: 32rem;
	}

	.stat-card {
		display: flex;
		flex-direction: column;
		gap: 0.3rem;
		padding: 0.9rem 1.1rem;
		background: var(--surface);
		border: 1px solid var(--border);
		border-radius: var(--radius-md);
		box-shadow: var(--shadow-sm);
	}

	.stat-label {
		font-size: 0.72rem;
		text-transform: uppercase;
		letter-spacing: 0.06em;
		color: var(--text-muted);
		font-weight: 600;
	}

	.stat-value {
		font-size: 1.6rem;
		font-weight: 650;
		letter-spacing: -0.02em;
	}

	.stat-enabled {
		color: var(--success-text);
	}

	.stat-disabled {
		color: var(--text-muted);
	}

	.create-user {
		margin: 0 0 2rem;
		padding: 1.15rem 1.25rem;
	}

	.create-user h2 {
		margin: 0 0 0.85rem;
		font-size: 0.92rem;
	}

	.create-user form {
		display: flex;
		align-items: flex-end;
		gap: 0.75rem;
	}

	.create-user label {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
		font-size: 0.82rem;
		font-weight: 500;
		color: var(--text-muted);
		flex: 1;
		max-width: 22rem;
	}

	.secret-reveal {
		margin-bottom: 1.75rem;
		display: flex;
		flex-direction: column;
		gap: 0.7rem;
	}

	.secret-header {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.secret-header svg {
		width: 17px;
		height: 17px;
		flex-shrink: 0;
	}

	.secret-title {
		margin: 0;
	}

	.secret-copy {
		margin: 0;
		font-size: 0.87rem;
	}

	.secret-row {
		display: flex;
		align-items: stretch;
		gap: 0.6rem;
	}

	.secret-value {
		padding: 0.55rem 0.75rem;
		background: var(--surface);
		border: 1px solid var(--warning-border);
		border-radius: var(--radius-sm);
		word-break: break-all;
		flex: 1;
		font-size: 0.85rem;
		display: flex;
		align-items: center;
	}

	.copy-btn {
		flex-shrink: 0;
		background: var(--surface);
	}

	.copy-btn.copied {
		background: var(--success-bg);
		border-color: var(--success-bg);
		color: var(--success-text);
	}

	.secret-actions {
		display: flex;
		gap: 0.6rem;
	}

	.dismiss-btn {
		padding-left: 0.3rem;
		padding-right: 0.3rem;
	}

	.error {
		color: var(--danger-text);
		background: var(--danger-bg);
		padding: 0.55rem 0.75rem;
		border-radius: var(--radius-sm);
		font-size: 0.85rem;
		margin-top: 0.85rem;
	}

	.empty {
		color: var(--text-muted);
	}

	.row-actions {
		display: flex;
		gap: 0.35rem;
		justify-content: flex-end;
	}

	.row-actions form {
		display: contents;
	}

	.row-actions button {
		font-size: 0.8rem;
		padding: 0.4rem 0.65rem;
	}
</style>
